# 필요 패키지 임포트

In [1]:
import pandas as pd
import numpy as np

# 데이터 불러오기

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/body/body.csv')

In [4]:
df

,측정나이,측정회원성별,신장 : cm,체중 : kg,체지방율 : %,이완기혈압(최저) : mmHg,수축기혈압(최고) : mmHg,악력D : kg,앉아윗몸앞으로굽히기 : cm,교차윗몸일으키기 : 회,제자리 멀리뛰기 : cm,등급
0,59.0,M,175.0,70.6,19.2,91.0,150.0,40.6,12.2,30.0,179.0,C
1,40.0,F,161.4,45.8,21.7,62.0,119.0,22.1,16.0,32.0,165.0,B
2,27.0,M,176.6,84.8,19.2,87.0,153.0,45.9,13.2,61.0,216.0,B
3,38.0,M,167.6,76.7,24.7,63.0,132.0,43.6,16.0,45.0,231.0,A
4,21.0,M,165.2,66.2,21.5,83.0,106.0,33.5,10.6,46.0,198.0,C
...,...,...,...,...,...,...,...,...,...,...,...,...
13391,61.0,M,167.0,65.8,22.2,71.0,130.0,33.7,14.5,37.0,182.0,C
13392,25.0,M,170.7,64.2,22.4,57.0,121.0,32.5,11.8,48.0,196.0,C
13393,47.0,M,166.2,77.5,22.8,84.0,133.0,52.4,11.9,45.0,220.0,B
13394,29.0,M,175.4,74.4,16.1,77.0,124.0,58.4,23.5,48.0,245.0,B
13395,28.0,M,173.8,78.5,17.3,88.0,119.0,50.1,19.9,57.0,237.0,A

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13396 entries, 0 to 13395
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   측정나이              13396 non-null  float64
 1   측정회원성별            13396 non-null  object
 2   신장 : cm           13396 non-null  float64
 3   체중 : kg           13396 non-null  float64
 4   체지방율 : %          13396 non-null  float64
 5   이완기혈압(최저) : mmHg  13396 non-null  float64
 6   수축기혈압(최고) : mmHg  13396 non-null  float64
 7   악력D : kg          13396 non-null  float64
 8   앉아윗몸앞으로굽히기 : cm   13396 non-null  float64
 9   교차윗몸일으키기 : 회      13396 non-null  float64
 10  제자리 멀리뛰기 : cm     13396 non-null  float64
 11  등급                13396 non-null  object
dtypes: float64(10), object(2)
memory usage: 1.2+ MB

# 문제

##Q1.  전체데이터의 수축기혈압(최고) - 이완기혈압(최저)의 평균을 구하여라

In [14]:
q1 = (df['수축기혈압(최고) : mmHg'] - df['이완기혈압(최저) : mmHg']).mean()

print(q1)

52.19539414750672

##Q2. 50~59세의 신장평균을 구하여라

In [39]:
q2 = df[(df.측정나이 >=50) & (df.측정나이 < 60)]['신장 : cm'].mean()

print(q2)

164.07490107405314

##Q3. 연령대 (20~29 : 20대 ...) 별  인원수를 구하여라

In [54]:
df['연령대'] = df['측정나이']//10 * 10
q3 = df['연령대'].value_counts()

print(q3)

20.0    5831
30.0    2660
40.0    1801
50.0    1769
60.0    1335
Name: 연령대, dtype: int64

##Q4.  연령대 (20~29 : 20대 ...) 별 등급의 숫자를 데이터 프레임으로 표현하라

In [63]:
q4 = df.groupby(['연령대','등급'], as_index = False).size()

print(q4)

     연령대 등급  size
0   20.0  A  1585
1   20.0  B  1443
2   20.0  C  1455
3   20.0  D  1348
4   30.0  A   743
5   30.0  B   697
6   30.0  C   626
7   30.0  D   594
8   40.0  A   386
9   40.0  B   428
10  40.0  C   455
11  40.0  D   532
12  50.0  A   321
13  50.0  B   410
14  50.0  C   474
15  50.0  D   564
16  60.0  A   314
17  60.0  B   371
18  60.0  C   339
19  60.0  D   311

##Q5. 남성 중 A등급과 D등급의 체지방률 평균의 차이(큰 값에서 작은 값의 차)를 구하여라

In [82]:
df_M = df[df.측정회원성별 == 'M']
q5 = df_M.groupby('등급')['체지방율 : %'].mean()

print(abs(q5[0]-q5[-1]))

7.932086486137521

##Q6. 여성 중 A등급과 D등급의 체중의 평균의 차이(큰 값에서 작은 값의 차)를 구하여라

In [83]:
df_F = df[df.측정회원성별 == 'F']
q6 = df_F.groupby('등급')['체중 : kg'].mean()

print(abs(q6[0]-q6[-1]))

5.176211590296489

##Q7. bmi는 자신의 몸무게(kg)를 신장/100의 제곱(m)으로 나눈값이다. 데이터의 bmi 를 구한 새로운 컬럼을 만들고 남성의 bmi 평균을 구하여라

In [92]:
df['bmi'] = df['체중 : kg'] / (df['신장 : cm']/100) **2
q7 = df[df.측정회원성별 == 'M']['bmi'].mean()
print(q7)

24.46134409819308

##Q8.  bmi보다 체지방율이 높은 사람들의 체중평균을 구하여라

In [93]:
q8 = df[df['체지방율 : %'] > df['bmi']]['체중 : kg'].mean()

print(q8)

61.7408806392542

##Q9. 남성과 여성의 악력 평균의 차이를 구하여라

In [94]:
q9 = df_M['악력D : kg'].mean() - df_F['악력D : kg'].mean()

print(q9)

17.55954185047464

##Q10.남성과 여성의 교차윗몸일으키기 횟수의 평균의 차이를 구하여라

In [96]:
q10 = df_M['교차윗몸일으키기 : 회'].mean() - df_F['교차윗몸일으키기 : 회'].mean()

print(q10)

14.243156833157627

In [97]:
cd '/content/drive/MyDrive/BigData/Exam'

/content/drive/MyDrive/BigData/Exam

In [ ]:
!git config --global user.name 'dydwns9436'
!git config --global user.email 'dydwns9436@naver.com'

!git commit -m '2022-06-24'

!git add Final_Test_03.ipynb
!git push