#모의고사 작업형 2회

## 제1 유형

### 데이터셋 : HR - Employee - Attrition.csv

In [391]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/BigData/CSV_File/HR-Employee-Attrition.csv')

In [392]:
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

###1.데이터에서 'Attrition'은 퇴사여부에 대한 종속변수이다. 종속변수의 값을 다음과 같이 수치로 변환해 새 컬럼으로 추가하고 각 범주별 레코드 수를 계산하시오.
(yes > 1, no > 2)

In [393]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Att_2'] = le.fit_transform(df['Attrition'])

df['Att_2'] = df['Att_2'].replace(0, 2)
df[['Att_2']]

      Att_2
0         1
1         2
2         1
3         2
4         2
...     ...
1465      2
1466      2
1467      2
1468      2
1469      2

[1470 rows x 1 columns]

In [394]:
df['Att_2'].value_counts()

2    1233
1     237
Name: Att_2, dtype: int64

###2.데이터셋의 데이터타입별 컬럼 개수를 계산하고, 범주형 변수 중 유일한 값을 1개만 가지고 있는 컬럼을 찾아 그 변수를 데이터에서 제거하시오.

In [395]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
 35  Att_2                     1470 non-null   int64
dtypes: int64(27), object(9)
memory usage: 413.6+ KB

In [396]:
cat_feat = df.select_dtypes('object', 'category').columns.values
df_cat = df[cat_feat].copy()
df_cat.nunique().sort_values()

Over18            1
Attrition         2
Gender            2
OverTime          2
BusinessTravel    3
Department        3
MaritalStatus     3
EducationField    6
JobRole           9
dtype: int64

In [397]:
df.drop('Over18', axis=1, inplace=True)

###3.원래 데이터에서 숫자형인 컬럼만 추출하여 새로운 df를 생성하고 각 변수간의 상관계수를 구하고 상관계수가 0.9 이상인 두개의 컬럼을 찾아 그 변수 중 하나를 제거하시오.

In [398]:
df_2 = pd.DataFrame(df.select_dtypes('int64'))

In [399]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   DailyRate                 1470 non-null   int64
 2   DistanceFromHome          1470 non-null   int64
 3   Education                 1470 non-null   int64
 4   EmployeeCount             1470 non-null   int64
 5   EmployeeNumber            1470 non-null   int64
 6   EnvironmentSatisfaction   1470 non-null   int64
 7   HourlyRate                1470 non-null   int64
 8   JobInvolvement            1470 non-null   int64
 9   JobLevel                  1470 non-null   int64
 10  JobSatisfaction           1470 non-null   int64
 11  MonthlyIncome             1470 non-null   int64
 12  MonthlyRate               1470 non-null   int64
 13  NumCompaniesWorked        1470 non-null   int64
 14  PercentSalaryHike         1470 non-null   int64
 15  PerformanceRating         1470 non-null   int64
 16  RelationshipSatisfaction  1470 non-null   int64
 17  StandardHours             1470 non-null   int64
 18  StockOptionLevel          1470 non-null   int64
 19  TotalWorkingYears         1470 non-null   int64
 20  TrainingTimesLastYear     1470 non-null   int64
 21  WorkLifeBalance           1470 non-null   int64
 22  YearsAtCompany            1470 non-null   int64
 23  YearsInCurrentRole        1470 non-null   int64
 24  YearsSinceLastPromotion   1470 non-null   int64
 25  YearsWithCurrManager      1470 non-null   int64
 26  Att_2                     1470 non-null   int64
dtypes: int64(27)
memory usage: 310.2 KB

In [400]:
df_corr = df_2.corr(method = 'pearson')

In [401]:
display((df_corr.iloc[:, :]>=0.9).count)

<bound method DataFrame.count of                             Age  DailyRate  DistanceFromHome  Education  \
Age                        True      False             False      False
DailyRate                 False       True             False      False
DistanceFromHome          False      False              True      False
Education                 False      False             False       True
EmployeeCount             False      False             False      False
EmployeeNumber            False      False             False      False
EnvironmentSatisfaction   False      False             False      False
HourlyRate                False      False             False      False
JobInvolvement            False      False             False      False
JobLevel                  False      False             False      False
JobSatisfaction           False      False             False      False
MonthlyIncome             False      False             False      False
MonthlyRate               False      False             False      False
NumCompaniesWorked        False      False             False      False
PercentSalaryHike         False      False             False      False
PerformanceRating         False      False             False      False
RelationshipSatisfaction  False      False             False      False
StandardHours             False      False             False      False
StockOptionLevel          False      False             False      False
TotalWorkingYears         False      False             False      False
TrainingTimesLastYear     False      False             False      False
WorkLifeBalance           False      False             False      False
YearsAtCompany            False      False             False      False
YearsInCurrentRole        False      False             False      False
YearsSinceLastPromotion   False      False             False      False
YearsWithCurrManager      False      False             False      False
Att_2                     False      False             False      False

                          EmployeeCount  EmployeeNumber  \
Age                               False           False
DailyRate                         False           False
DistanceFromHome                  False           False
Education                         False           False
EmployeeCount                     False           False
EmployeeNumber                    False            True
EnvironmentSatisfaction           False           False
HourlyRate                        False           False
JobInvolvement                    False           False
JobLevel                          False           False
JobSatisfaction                   False           False
MonthlyIncome                     False           False
MonthlyRate                       False           False
NumCompaniesWorked                False           False
PercentSalaryHike                 False           False
PerformanceRating                 False           False
RelationshipSatisfaction          False           False
StandardHours                     False           False
StockOptionLevel                  False           False
TotalWorkingYears                 False           False
TrainingTimesLastYear             False           False
WorkLifeBalance                   False           False
YearsAtCompany                    False           False
YearsInCurrentRole                False           False
YearsSinceLastPromotion           False           False
YearsWithCurrManager              False           False
Att_2                             False           False

                          EnvironmentSatisfaction  HourlyRate  JobInvolvement  \
Age                                         False       False           False
DailyRate                                   False       False           False
DistanceFromHome                            False       False           False
Education                                   False       False           False
EmployeeCount                               False       False           False
EmployeeNumber                              False       False           False
EnvironmentSatisfaction                      True       False           False
HourlyRate                                  False        True           False
JobInvolvement                              False       False            True
JobLevel                                    False       False           False
JobSatisfaction                             False       False           False
MonthlyIncome                               False       False           False
MonthlyRate                                 False       False           False
NumCompaniesWorked                          False       False           False
PercentSalaryHike                           False       False           False
PerformanceRating                           False       False           False
RelationshipSatisfaction                    False       False           False
StandardHours                               False       False           False
StockOptionLevel                            False       False           False
TotalWorkingYears                           False       False           False
TrainingTimesLastYear                       False       False           False
WorkLifeBalance                             False       False           False
YearsAtCompany                              False       False           False
YearsInCurrentRole                          False       False           False
YearsSinceLastPromotion                     False       False           False
YearsWithCurrManager                        False       False           False
Att_2                                       False       False           False

                          JobLevel  ...  StandardHours  StockOptionLevel  \
Age                          False  ...          False             False
DailyRate                    False  ...          False             False
DistanceFromHome             False  ...          False             False
Education                    False  ...          False             False
EmployeeCount                False  ...          False             False
EmployeeNumber               False  ...          False             False
EnvironmentSatisfaction      False  ...          False             False
HourlyRate                   False  ...          False             False
JobInvolvement               False  ...          False             False
JobLevel                      True  ...          False             False
JobSatisfaction              False  ...          False             False
MonthlyIncome                 True  ...          False             False
MonthlyRate                  False  ...          False             False
NumCompaniesWorked           False  ...          False             False
PercentSalaryHike            False  ...          False             False
PerformanceRating            False  ...          False             False
RelationshipSatisfaction     False  ...          False             False
StandardHours                False  ...          False             False
StockOptionLevel             False  ...          False              True
TotalWorkingYears            False  ...          False             False
TrainingTimesLastYear        False  ...          False             False
WorkLifeBalance              False  ...          False             False
YearsAtCompany               False  ...          False             False
YearsInCurrentRole           False  ...          False             False
YearsSinceLastPromotion      False  ...          False             False
YearsWithCurrManager         False  ...          False             False
Att_2                        False  ...          False             False

                          TotalWorkingYears  TrainingTimesLastYear  \
Age                                   False                  False
DailyRate                             False                  False
DistanceFromHome                      False                  False
Education                             False                  False
EmployeeCount                         False                  False
EmployeeNumber                        False                  False
EnvironmentSatisfaction               False                  False
HourlyRate                            False                  False
JobInvolvement                        False                  False
JobLevel                              False                  False
JobSatisfaction                       False                  False
MonthlyIncome                         False                  False
MonthlyRate                           False                  False
NumCompaniesWorked                    False                  False
PercentSalaryHike                     False                  False
PerformanceRating                     False                  False
RelationshipSatisfaction              False                  False
StandardHours                         False                  False
StockOptionLevel                      False                  False
TotalWorkingYears                      True                  False
TrainingTimesLastYear                 False                   True
WorkLifeBalance                       False                  False
YearsAtCompany                        False                  False
YearsInCurrentRole                    False                  False
YearsSinceLastPromotion               False                  False
YearsWithCurrManager                  False                  False
Att_2                                 False                  False

                          WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
Age                                 False           False               False
DailyRate                           False           False               False
DistanceFromHome                    False           False               False
Education                           False           False               False
EmployeeCount                       False           False               False
EmployeeNumber                      False           False               False
EnvironmentSatisfaction             False           False               False
HourlyRate                          False           False               False
JobInvolvement                      False           False               False
JobLevel                            False           False               False
JobSatisfaction                     False           False               False
MonthlyIncome                       False           False               False
MonthlyRate                         False           False               False
NumCompaniesWorked                  False           False               False
PercentSalaryHike                   False           False               False
PerformanceRating                   False           False               False
RelationshipSatisfaction            False           False               False
StandardHours                       False           False               False
StockOptionLevel                    False           False               False
TotalWorkingYears                   False           False               False
TrainingTimesLastYear               False           False               False
WorkLifeBalance                      True           False               False
YearsAtCompany                      False            True               False
YearsInCurrentRole                  False           False                True
YearsSinceLastPromotion             False           False               False
YearsWithCurrManager                False           False               False
Att_2                               False           False               False

                          YearsSinceLastPromotion  YearsWithCurrManager  Att_2
Age                                         False                 False  False
DailyRate                                   False                 False  False
DistanceFromHome                            False                 False  False
Education                                   False                 False  False
EmployeeCount                               False                 False  False
EmployeeNumber                              False                 False  False
EnvironmentSatisfaction                     False                 False  False
HourlyRate                                  False                 False  False
JobInvolvement                              False                 False  False
JobLevel                                    False                 False  False
JobSatisfaction                             False                 False  False
MonthlyIncome                               False                 False  False
MonthlyRate                                 False                 False  False
NumCompaniesWorked                          False                 False  False
PercentSalaryHike                           False                 False  False
PerformanceRating                           False                 False  False
RelationshipSatisfaction                    False                 False  False
StandardHours                               False                 False  False
StockOptionLevel                            False                 False  False
TotalWorkingYears                           False                 False  False
TrainingTimesLastYear                       False                 False  False
WorkLifeBalance                             False                 False  False
YearsAtCompany                              False                 False  False
YearsInCurrentRole                          False                 False  False
YearsSinceLastPromotion                      True                 False  False
YearsWithCurrManager                        False                  True  False
Att_2                                       False                 False   True

[27 rows x 27 columns]>

## 제 2유형

### 데이터셋 : Parkinsons.csv

Q. 데이터셋을 이용해 파킨슨병을 예측하는 모델을 로지스틱 회귀모형을 적용해 생성하고, 이때 파킨슨병을 예측하는데 영향을 미치는 변수를 중요한 순서대로 3개 선정하시오.

> 분석조건

1. name 컬럼 제거 
2. 정규화는 최소최대정규화 적용
3. 로지스틱 회귀를 위해 상수항 추가
4. Status는 카테고리 타입으로 변환
5. 트레이닝셋과 테스트셋의 비율은 9:1
6. 최적화 방법론으로 'bfgs' 사용

In [402]:
df = pd.read_csv('/content/drive/MyDrive/BigData/CSV_File/Parkinsons.csv')

In [403]:
df.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [404]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              195 non-null    object
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 17  status            195 non-null    int64
 18  RPDE              195 non-null    float64
 19  DFA               195 non-null    float64
 20  spread1           195 non-null    float64
 21  spread2           195 non-null    float64
 22  D2                195 non-null    float64
 23  PPE               195 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.7+ KB

In [405]:
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [406]:
df = df.drop('name',axis = 1)

In [407]:
df.select_dtypes('object').columns

Index([], dtype='object')

In [408]:
df['status'] = df['status'].astype('category')

In [409]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MDVP:Fo(Hz)       195 non-null    float64
 1   MDVP:Fhi(Hz)      195 non-null    float64
 2   MDVP:Flo(Hz)      195 non-null    float64
 3   MDVP:Jitter(%)    195 non-null    float64
 4   MDVP:Jitter(Abs)  195 non-null    float64
 5   MDVP:RAP          195 non-null    float64
 6   MDVP:PPQ          195 non-null    float64
 7   Jitter:DDP        195 non-null    float64
 8   MDVP:Shimmer      195 non-null    float64
 9   MDVP:Shimmer(dB)  195 non-null    float64
 10  Shimmer:APQ3      195 non-null    float64
 11  Shimmer:APQ5      195 non-null    float64
 12  MDVP:APQ          195 non-null    float64
 13  Shimmer:DDA       195 non-null    float64
 14  NHR               195 non-null    float64
 15  HNR               195 non-null    float64
 16  status            195 non-null    category
 17  RPDE              195 non-null    float64
 18  DFA               195 non-null    float64
 19  spread1           195 non-null    float64
 20  spread2           195 non-null    float64
 21  D2                195 non-null    float64
 22  PPE               195 non-null    float64
dtypes: category(1), float64(22)
memory usage: 34.0 KB

In [410]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

mms = MinMaxScaler()

df_mms = mms.fit_transform(df)
df_mms = pd.DataFrame(df_mms)

In [411]:
df_mms.columns = df.columns

In [412]:
df_mms[['status']]

     status
0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
..      ...
190     0.0
191     0.0
192     0.0
193     0.0
194     0.0

[195 rows x 1 columns]

In [413]:
# 상수항 추가 (상수항 추가는 왜하는지 더 배워봐야 겠다.)

import statsmodels.api as sm

df_mms = sm.add_constant(df_mms, has_constant = 'add')

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/tsatools.py:117: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [414]:
df_mms.tail()

,const,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
190,1.0,0.499820,0.262986,0.165722,0.092440,0.090909,0.093931,0.089496,0.094076,0.286014,...,0.362306,0.085909,0.450134,0.0,0.447684,0.333127,0.257894,0.260408,0.549049,0.183318
191,1.0,0.705488,0.307974,0.138243,0.125794,0.090909,0.126686,0.107181,0.126826,0.164050,...,0.221338,0.055543,0.435097,0.0,0.408567,0.434101,0.319956,0.276956,0.605474,0.257558
192,1.0,0.502730,0.281413,0.050727,0.378653,0.288538,0.267823,0.252947,0.267940,0.123608,...,0.156631,0.338988,0.383728,0.0,0.352318,0.324299,0.212945,0.342577,0.558967,0.180580
193,1.0,0.642893,0.601807,0.054279,0.181703,0.130435,0.145472,0.159700,0.145288,0.122512,...,0.155989,0.227838,0.429936,0.0,0.454176,0.277579,0.220650,0.452885,0.318222,0.163137
194,1.0,0.733274,0.322794,0.071948,0.126747,0.090909,0.109345,0.120579,0.109327,0.084900,...,0.110027,0.137919,0.518898,0.0,0.481200,0.358856,0.405161,0.415095,0.503673,0.215460

In [415]:
X = df_mms.drop('status', axis = 1)
y = df_mms['status']

In [416]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify = y, random_state=20220621)

print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(175, 23) (175,)
(20, 23) (20,)

In [417]:
lg = sm.Logit(y_train, X_train) #로지스틱 회귀 생성(여기서는 신기하게 종속변수가 먼저오고 독립변수가 그 후에 온다.)

sett = lg.fit(method = 'bfgs', maxiter = 1000)

Optimization terminated successfully.
         Current function value: 0.222346
         Iterations: 314
         Function evaluations: 315
         Gradient evaluations: 315

In [418]:
sett.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                 status   No. Observations:                  175
Model:                          Logit   Df Residuals:                      152
Method:                           MLE   Df Model:                           22
Date:                Mon, 20 Jun 2022   Pseudo R-squ.:                  0.6012
Time:                        18:06:00   Log-Likelihood:                -38.911
converged:                       True   LL-Null:                       -97.576
Covariance Type:            nonrobust   LLR p-value:                 5.313e-15
====================================================================================
                       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------
const               -2.3964      5.945     -0.403      0.687     -14.048       9.255
MDVP:Fo(Hz)         -2.7748      3.747     -0.740      0.459     -10.119       4.570
MDVP:Fhi(Hz)        -0.9185      2.141     -0.429      0.668      -5.114       3.277
MDVP:Flo(Hz)        -0.0566      2.051     -0.028      0.978      -4.077       3.964
MDVP:Jitter(%)     -37.9667     38.139     -0.995      0.320    -112.718      36.785
MDVP:Jitter(Abs)    -6.7656     24.152     -0.280      0.779     -54.102      40.571
MDVP:RAP            43.8568   2893.455      0.015      0.988   -5627.211    5714.924
MDVP:PPQ           -57.9125     38.806     -1.492      0.136    -133.971      18.146
Jitter:DDP          44.0001   2897.346      0.015      0.988   -5634.693    5722.693
MDVP:Shimmer        65.7532    122.636      0.536      0.592    -174.608     306.115
MDVP:Shimmer(dB)     6.8130     43.819      0.155      0.876     -79.071      92.697
Shimmer:APQ3       -28.0914   6502.149     -0.004      0.997   -1.28e+04    1.27e+04
Shimmer:APQ5        -6.2148     38.066     -0.163      0.870     -80.823      68.394
MDVP:APQ            13.4651     54.256      0.248      0.804     -92.874     119.805
Shimmer:DDA        -25.8080   6504.795     -0.004      0.997   -1.28e+04    1.27e+04
NHR                  8.7278     15.557      0.561      0.575     -21.764      39.220
HNR                 -2.0739      5.889     -0.352      0.725     -13.616       9.468
RPDE                -3.7491      2.268     -1.653      0.098      -8.193       0.695
DFA                  2.5058      2.462      1.018      0.309      -2.320       7.332
spread1             -1.3019      9.866     -0.132      0.895     -20.638      18.035
spread2              7.2590      3.285      2.210      0.027       0.821      13.697
D2                  -0.1979      3.431     -0.058      0.954      -6.922       6.527
PPE                 19.2877     12.799      1.507      0.132      -5.797      44.373
====================================================================================

Possibly complete quasi-separation: A fraction 0.11 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [419]:
def cut_off(y, threshold):
    Y =y.copy()
    Y[Y>threshold]=1
    Y[Y<=threshold] = 0

    return(Y.astype(int))

In [420]:
pred = sett.predict(X_test)
y_pred = cut_off(pred, 0.5)

In [421]:
from sklearn.metrics import f1_score

f1_score(y_test, y_pred)

0.9090909090909091

In [425]:
cd /content/drive/MyDrive/BigData/Exam

/content/drive/MyDrive/BigData/Exam

In [426]:
!git config --global user.name 'dydwns9436'
!git config --global user.email 'dydwns9436@naver.com'

!git commit -m '2022-06-21'

!git add Moak_Exam_02.ipynb
!git push

[main da46ec9] 2022-06-21
 1 file changed, 1 insertion(+)
 create mode 100644 Moak_Exam_02.ipynb
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 15.55 KiB | 2.59 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/dydwns9436/BigData_Exam.git
   c5559af..da46ec9  main -> main